// examples/react-query/src/App.tsx
import { type SubmitEvent, useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { add, getServerTime, sayHi } from "./api";
import { getError, isValiError, type ValiError } from "./util/helpers";

const GREETING = "Jane";
const RPC_PREFIX = "__A_server";

export const greetingKey = ["sayHi", GREETING] as const;

export function fetchGreeting() {
  return sayHi(GREETING).data;
}

function isAddError(
  result: Awaited<ReturnType<typeof add>["data"]> | undefined,
): result is { error: ValiError } {
  return (
    typeof result === "object" &&
    result !== null &&
    "error" in result &&
    isValiError(result.error)
  );
}

function Greeting() {
  const query = useQuery({
    queryKey: greetingKey,
    queryFn: fetchGreeting,
  });

  return (
    <h1>
      {query.isPending
        ? "Hello World!"
        : query.isError
        ? "Hello Error!"
        : query.data}
    </h1>
  );
}

function AddForm() {
  const cancelRef = useRef<((reason: string) => void) | null>(null);

  const mutation = useMutation({
    mutationFn: async (payload: string) => {
      const { data, cancel } = add(payload);
      cancelRef.current = cancel;
      try {
        return await data;
      } finally {
        cancelRef.current = null;
      }
    },
  });

  const result = mutation.data;
  const hasErrors = isAddError(result);

  const errorA = hasErrors ? getError(result.error, "a") : "";
  const errorB = hasErrors ? getError(result.error, "b") : "";

  const onSubmit = (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    mutation.mutate(JSON.stringify(Object.fromEntries(formData.entries())));
  };

  const onCancel = () => {
    cancelRef.current?.("Client disconnected");
    mutation.reset();
  };

  return (
    <form id="addForm" onSubmit={onSubmit}>
      <h2>Form</h2>
      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
        <label htmlFor="a">A</label>
        <div className="form-input">
          <input id="a" name="a" type="number" placeholder="Value A" />
          <div id="error-a" style={{ color: "red" }}>
            {errorA}
          </div>
        </div>
      </div>

      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
        <label htmlFor="b">B</label>
        <div className="form-input">
          <input id="b" name="b" type="text" placeholder="Value B" />
          <div id="error-b" style={{ color: "red" }}>
            {errorB}
          </div>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
        <label htmlFor="output">&gt;</label>
        <output id="output">
          {hasErrors ? "Result: Error" : `Result: ${String(result ?? 0)}`}
        </output>

        <button type="submit" disabled={mutation.isPending}>
          {mutation.isPending ? "Adding…" : "Add"}
        </button>
        <button
          id="cancelBtn"
          type="button"
          onClick={onCancel}
          disabled={!mutation.isPending}
        >
          Cancel
        </button>
      </div>
    </form>
  );
}

function TimeForm() {
  const [locale, setLocale] = useState("en-US");

  const query = useQuery({
    queryKey: ["getServerTime", locale],
    queryFn: () => {
      const { data } = getServerTime(locale);
      return data;
    },
    enabled: false,
  });

  const link = `/${RPC_PREFIX}/get-server-time?args=${
    encodeURIComponent(JSON.stringify([locale]))
  }`;

  const onSubmit = (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    query.refetch();
  };

  return (
    <form id="timeForm" onSubmit={onSubmit}>
      <h2>GET</h2>
      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
        <label htmlFor="locale">Locale</label>
        <div className="form-input">
          <input
            id="locale"
            name="locale"
            type="text"
            placeholder="en-US"
            value={locale}
            onChange={(e) => setLocale(e.target.value)}
          />
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
        <label htmlFor="time-output">&gt;</label>
        <output id="time-output">
          {query.isFetching
            ? "Fetching…"
            : query.data
            ? `Time: ${query.data.time}`
            : "Time: —"}
        </output>
        <button type="submit" disabled={query.isFetching}>
          {query.isFetching ? "Fetching…" : "Get time"}
        </button>
        <a id="time-link" href={link} target="_blank">
          Open in new tab
        </a>
      </div>
    </form>
  );
}

export function App() {
  return (
    <>
      <Greeting />
      <p className="read-the-docs">
        SSR Example using <code>@thednp/rpc</code> with{" "}
        <code>@tanstack/react-query</code>
      </p>
      <AddForm />
      <TimeForm />
    </>
  );
}

// examples/solid-query/src/App.tsx
import { createMemo, createSignal } from "solid-js";
import { createMutation, createQuery } from "@tanstack/solid-query";
import { add, getServerTime, sayHi } from "./api";
import { getError, isValiError, type ValiError } from "./util/helpers";

const GREETING = "Jane";
const RPC_PREFIX = "__A_server";

export const greetingKey = ["sayHi", GREETING] as const;

export function fetchGreeting() {
  return sayHi(GREETING).data;
}

function isAddError(
  result: Awaited<ReturnType<typeof add>["data"]> | undefined,
): result is { error: ValiError } {
  return (
    typeof result === "object" &&
    result !== null &&
    "error" in result &&
    isValiError(result.error)
  );
}

function Greeting() {
  const query = createQuery(() => ({
    queryKey: greetingKey,
    queryFn: fetchGreeting,
  }));

  return (
    <h1>
      {query.isPending
        ? "Hello World!"
        : query.isError
        ? "Hello Error!"
        : query.data}
    </h1>
  );
}

function AddForm() {
  let cancel: ((reason: string) => void) | null = null;

  const mutation = createMutation(() => ({
    mutationFn: async (payload: string) => {
      const { data, cancel: cancelFn } = add(payload);
      cancel = cancelFn;
      try {
        return await data;
      } finally {
        cancel = null;
      }
    },
  }));

  const result = createMemo(() => mutation.data);
  const errors = createMemo(() => {
    const value = result();
    return isAddError(value)
      ? {
        has: true,
        a: getError(value.error, "a"),
        b: getError(value.error, "b"),
      }
      : { has: false, a: "", b: "" };
  });

  const onSubmit = (e: SubmitEvent) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    mutation.mutate(JSON.stringify(Object.fromEntries(formData.entries())));
  };

  const onCancel = () => {
    cancel?.("Client disconnected");
    mutation.reset();
  };

  return (
    <form id="addForm" onSubmit={onSubmit}>
      <h2>Form</h2>
      <div style={{ display: "flex", "align-items": "center", gap: "0.5rem" }}>
        <label for="a">A</label>
        <div class="form-input">
          <input id="a" name="a" type="number" placeholder="Value A" />
          <div id="error-a" style={{ color: "red" }}>
            {errors().a}
          </div>
        </div>
      </div>

      <div style={{ display: "flex", "align-items": "center", gap: "10px" }}>
        <label for="b">B</label>
        <div class="form-input">
          <input id="b" name="b" type="text" placeholder="Value B" />
          <div id="error-b" style={{ color: "red" }}>
            {errors().b}
          </div>
        </div>
      </div>
      <div style={{ display: "flex", "align-items": "center", gap: "10px" }}>
        <label for="output">&gt;</label>
        <output id="output">
          {errors().has ? "Result: Error" : `Result: ${String(result() ?? 0)}`}
        </output>

        <button type="submit" disabled={mutation.isPending}>
          {mutation.isPending ? "Adding…" : "Add"}
        </button>
        <button
          id="cancelBtn"
          type="button"
          onClick={onCancel}
          disabled={!mutation.isPending}
        >
          Cancel
        </button>
      </div>
    </form>
  );
}

function TimeForm() {
  const [locale, setLocale] = createSignal("en-US");

  const query = createQuery(() => ({
    queryKey: ["getServerTime", locale()],
    queryFn: () => {
      const { data } = getServerTime(locale());
      return data;
    },
    enabled: false,
  }));

  const link = () =>
    `/${RPC_PREFIX}/get-server-time?args=${
      encodeURIComponent(JSON.stringify([locale()]))
    }`;

  const onSubmit = (e: SubmitEvent) => {
    e.preventDefault();
    query.refetch();
  };

  return (
    <form id="timeForm" onSubmit={onSubmit}>
      <h2>GET</h2>
      <div style={{ display: "flex", "align-items": "center", gap: "0.5rem" }}>
        <label for="locale">Locale</label>
        <div class="form-input">
          <input
            id="locale"
            name="locale"
            type="text"
            placeholder="en-US"
            value={locale()}
            onInput={(e) => setLocale(e.currentTarget.value)}
          />
        </div>
      </div>
      <div style={{ display: "flex", "align-items": "center", gap: "10px" }}>
        <label for="time-output">&gt;</label>
        <output id="time-output">
          {query.isFetching
            ? "Fetching…"
            : query.data
            ? `Time: ${query.data.time}`
            : "Time: —"}
        </output>
        <button type="submit" disabled={query.isFetching}>
          {query.isFetching ? "Fetching…" : "Get time"}
        </button>
        <a id="time-link" href={link()} target="_blank">
          Open in new tab
        </a>
      </div>
    </form>
  );
}

export function App() {
  return (
    <>
      <Greeting />
      <p class="read-the-docs">
        SSR Example using <code>@thednp/rpc</code> with{" "}
        <code>@tanstack/solid-query</code>
      </p>
      <AddForm />
      <TimeForm />
    </>
  );
}
